name: parctice_flutter_from_flutter_channel
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: '>=3.0.5 <4.0.0'
dependencies:
  animated_text_kit: ^4.2.2
  animations: ^2.0.7
  cached_network_image: ^3.2.3
  carousel_slider: ^4.2.1
 # cloud_firestore: ^4.8.0
  colorful_safe_area: ^1.0.0
  connectivity_plus: ^4.0.1
  cupertino_icons: ^1.0.2
  curved_navigation_bar: ^1.0.3
  device_info_plus: ^9.0.3
  easy_localization: ^3.0.1
  firebase_auth: ^4.6.2
  firebase_core: ^2.15.1
  firebase_crashlytics: ^3.3.3
  flame: ^1.8.1
  flutter:
    sdk: flutter
  flutter_animate: ^4.2.0
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  flutter_rating_bar: ^4.0.1
  flutter_slidable: ^3.0.0
  font_awesome_flutter: ^10.5.0
  get: ^4.6.5
  go_router: ^9.0.0
  google_fonts: ^2.0.0
  http: ^0.13.5
  image_picker: ^1.0.7
 # intl: 0.18.0
  path_provider: ^2.1.0
  firebase_ui_auth: ^1.6.4

  provider: ^6.0.5
  shared_preferences: ^2.0.20
  skeletons: ^0.0.3
  url_launcher: ^6.1.11

  dio: ^5.4.0
  camera: ^0.10.5+9
  gal: ^2.2.3
dev_dependencies:
  flutter_lints: ^2.0.0
  #  fluttertoast: ^8.2.2
  flutter_test:
    sdk: flutter
  linter: null
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
